-- V3 — USERS 테이블을 USER.md ERD 에 맞게 변경.
-- V1 컬럼(name·picture·google_sub·role)을 ERD 확정 컬럼으로 교체한다.

-- 1. 컬럼 이름 변경
ALTER TABLE USERS
    RENAME COLUMN name          TO NICKNAME,
    RENAME COLUMN picture       TO PROFILE_IMG_URL,
    RENAME COLUMN role          TO SYSTEM_ROLE;

-- 2. 타입·크기 맞춤 (NOT NULL DEFAULT '' 는 기존 데이터 보호용 임시 기본값)
ALTER TABLE USERS
    MODIFY COLUMN NICKNAME        VARCHAR(255) NOT NULL DEFAULT '',
    MODIFY COLUMN PROFILE_IMG_URL VARCHAR(2048)   NULL,
    MODIFY COLUMN SYSTEM_ROLE    VARCHAR(20)  NOT NULL;

-- 3. SYSTEM_ROLE 값 정규화 (V1 기본값 STUDENT·OPERATOR → MEMBER)
UPDATE USERS SET SYSTEM_ROLE = 'MEMBER' WHERE SYSTEM_ROLE IN ('STUDENT', 'OPERATOR');

-- 4. 임시 DEFAULT 제거
ALTER TABLE USERS ALTER COLUMN NICKNAME DROP DEFAULT;

-- 5. google_sub 제거 — 인증 수단 식별자는 USER_IDENTITY 로
ALTER TABLE USERS DROP COLUMN google_sub;

-- 6. ERD 신규 컬럼 추가 (모두 nullable 로 시작)
ALTER TABLE USERS
    ADD COLUMN JOB_TITLE      VARCHAR(100) NULL,
    ADD COLUMN COUNTRY_CODE   CHAR(2)      NULL,
    ADD COLUMN CITY           VARCHAR(100) NULL,
    ADD COLUMN REGION_GROUP   VARCHAR(20)  NULL,
    ADD COLUMN TIME_ZONE      VARCHAR(64)  NULL,
    ADD COLUMN DISCORD_ID     VARCHAR(64)  NULL,
    ADD COLUMN DISCORD_HANDLE VARCHAR(64)  NULL;

-- 7. DISCORD_ID 유니크 (NULL 허용 — MySQL UNIQUE 는 NULL 여럿 허용)
ALTER TABLE USERS ADD CONSTRAINT uk_users_discord_id UNIQUE (DISCORD_ID);
