-- V16 — STUDY_PROGRAM의 기수별 속성을 STUDY로 이전 + COHORT 컬럼 추가

-- 1-1. STUDY에 컬럼 추가
ALTER TABLE STUDY
    ADD COLUMN TITLE            VARCHAR(200),
    ADD COLUMN SLUG             VARCHAR(100),
    ADD COLUMN ONE_LINE_SUMMARY VARCHAR(255),
    ADD COLUMN DESCRIPTION      TEXT,
    ADD COLUMN CATEGORY         VARCHAR(50),
    ADD COLUMN STUDY_KIND       VARCHAR(20),
    ADD COLUMN THUMBNAIL_URL    VARCHAR(2048),
    ADD COLUMN IS_HIDDEN        TINYINT(1) NOT NULL DEFAULT 0;

-- 1-2. SLUG 유니크 인덱스 이전
ALTER TABLE STUDY_PROGRAM DROP INDEX uk_study_program_slug;
CREATE UNIQUE INDEX uk_study_slug ON STUDY (SLUG);

-- 1-3. STUDY_PROGRAM에서 이전된 컬럼 제거
ALTER TABLE STUDY_PROGRAM
    DROP COLUMN SLUG,
    DROP COLUMN ONE_LINE_SUMMARY,
    DROP COLUMN DESCRIPTION,
    DROP COLUMN CATEGORY,
    DROP COLUMN STUDY_KIND,
    DROP COLUMN THUMBNAIL_URL,
    DROP COLUMN IS_HIDDEN;
