-- V17 — 날짜 컬럼명을 <name>_AT 형식으로 통일 + RECRUIT_DEADLINE_AT 을 STUDY → STUDY_RECRUITMENT 으로 이동.

-- STUDY: RECRUIT_DEADLINE 삭제 (모집 마감은 STUDY_RECRUITMENT.RECRUIT_DEADLINE_AT 로 이동),
--        나머지 날짜 컬럼 rename
ALTER TABLE STUDY
    DROP COLUMN RECRUIT_DEADLINE,
    RENAME COLUMN START_DATE TO START_AT,
    RENAME COLUMN END_DATE TO END_AT,
    RENAME COLUMN PUBLISH_DATE TO PUBLISH_AT;

ALTER TABLE STUDY_PROPOSAL
    RENAME COLUMN PROPOSED_DATE TO PROPOSED_AT;

-- STUDY_RECRUITMENT: CLOSE_AT → RECRUIT_DEADLINE_AT (역할 명확화 — 계획된 마감 시각)
ALTER TABLE STUDY_RECRUITMENT
    RENAME COLUMN CLOSE_AT TO RECRUIT_DEADLINE_AT;

ALTER TABLE STUDY_RECRUITMENT
    RENAME INDEX idx_study_recruitment_cohort TO idx_study_recruitment_study;
