-- V20 — StudyCategory enum 정리: 14개 → 11개 (기획 화면의 canonical 목록에 맞춘다).
-- CS → ALGORITHM, BACKEND·FRONTEND·MOBILE → SOFTWARE, PLANNING·PM → PRODUCT, DESIGN → OTHER.
-- BOOK_CLUB 은 새 값이라 옮길 데이터가 없다.

UPDATE STUDY SET CATEGORY = 'ALGORITHM' WHERE CATEGORY = 'CS';
UPDATE STUDY SET CATEGORY = 'SOFTWARE' WHERE CATEGORY IN ('BACKEND', 'FRONTEND', 'MOBILE');
UPDATE STUDY SET CATEGORY = 'PRODUCT' WHERE CATEGORY IN ('PLANNING', 'PM');
UPDATE STUDY SET CATEGORY = 'OTHER' WHERE CATEGORY = 'DESIGN';
