-- V31 — 스터디 일정 보드 (specs/study-meeting/spec.md 결정 10 · 11 · 12).
--
-- STUDY_MEETING.MEETING_TYPE      KICKOFF · REGULAR. 분반마다 킥오프 하나(번호 0), 출석률에서 뺀다.
--                                 데이터가 있는 테이블이라 NULL 로 더하고 → 채우고 → NOT NULL 로 바꾼다 (database-guide).
-- STUDY_MEETING.PRESENTER1/2_*    발표자 칸 → STUDY_PARTICIPANT.ID. 애그리거트 사이라 FK 없이 ID 참조.
-- STUDY_GROUP.RULES               스터디 규칙. 500자까지.

ALTER TABLE STUDY_MEETING ADD COLUMN MEETING_TYPE VARCHAR(16) NULL;
UPDATE STUDY_MEETING SET MEETING_TYPE = 'REGULAR' WHERE MEETING_TYPE IS NULL;
ALTER TABLE STUDY_MEETING MODIFY COLUMN MEETING_TYPE VARCHAR(16) NOT NULL DEFAULT 'REGULAR';

ALTER TABLE STUDY_MEETING
    ADD COLUMN PRESENTER1_PARTICIPANT_ID BIGINT NULL,
    ADD COLUMN PRESENTER2_PARTICIPANT_ID BIGINT NULL;

ALTER TABLE STUDY_GROUP ADD COLUMN RULES VARCHAR(500) NULL;
