-- V6 — StudyCategory enum 확장: 8개 → 14개.
-- 기존 값 변환: AI → AI_ML, PAPER → CS, PRODUCT → PM.

UPDATE STUDY SET CATEGORY = 'AI_ML' WHERE CATEGORY = 'AI';
UPDATE STUDY SET CATEGORY = 'CS' WHERE CATEGORY = 'PAPER';
UPDATE STUDY SET CATEGORY = 'PM' WHERE CATEGORY = 'PRODUCT';
