-- STUDY_BOOKMARK.STUDY_ID → STUDY_COHORT_ID
-- 북마크 단위를 스터디에서 기수(STUDY_COHORT)로 변경한다.

ALTER TABLE STUDY_BOOKMARK CHANGE COLUMN STUDY_ID STUDY_COHORT_ID BIGINT NOT NULL;

ALTER TABLE STUDY_BOOKMARK DROP INDEX uk_study_bookmark_account_study;
ALTER TABLE STUDY_BOOKMARK ADD CONSTRAINT uk_study_bookmark_account_cohort UNIQUE (ACCOUNT_ID, STUDY_COHORT_ID);

ALTER TABLE STUDY_BOOKMARK DROP INDEX idx_study_bookmark_study;
ALTER TABLE STUDY_BOOKMARK ADD INDEX idx_study_bookmark_cohort (STUDY_COHORT_ID);
